version = 0.1
[default.deploy.parameters]
stack_name = "contact-form-stack"
resolve_s3 = true
s3_prefix = "contact-form-stack"
region = "ap-southeast-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []
